//! Phase 21 (Track M.3) — Django migration adapter (Python).
//!
//! Fires when the surrounding source imports `django.db.migrations` and
//! declares a `Migration` class with `operations = [...]`.

use crate::dynamic::framework::{FrameworkAdapter, FrameworkBinding};
use crate::evidence::EntryKind;
use crate::summary::FuncSummary;
use crate::symbol::Lang;

pub struct MigrationDjangoAdapter;

const ADAPTER_NAME: &str = "migration-django";

fn source_imports_django_migration(file_bytes: &[u8]) -> bool {
    const NEEDLES: &[&[u8]] = &[
        b"django.db.migrations",
        b"migrations.Migration",
        b"migrations.RunPython",
        b"operations = [",
        b"dependencies = [",
        b"from django.db import migrations",
    ];
    NEEDLES
        .iter()
        .any(|n| file_bytes.windows(n.len()).any(|w| w == *n))
}

fn extract_version(file_bytes: &[u8]) -> Option<String> {
    // Django migrations carry a numeric prefix on the filename
    // (`0001_initial.py`); the version is more reliably the prefix of
    // the file path, but we can also pull a top-level `# Version: NNNN`
    // comment.  Best-effort.
    let text = std::str::from_utf8(file_bytes).unwrap_or("");
    let needle = "# Generated by Django ";
    if let Some(idx) = text.find(needle) {
        let after = &text[idx + needle.len()..];
        if let Some(end) = after.find([' ', '\n']) {
            return Some(after[..end].trim().to_owned());
        }
    }
    None
}

fn name_is_django_migration_entry(name: &str) -> bool {
    matches!(
        name,
        "Migration" | "upgrade" | "downgrade" | "forwards" | "backwards"
    )
}

impl FrameworkAdapter for MigrationDjangoAdapter {
    fn name(&self) -> &'static str {
        ADAPTER_NAME
    }

    fn lang(&self) -> Lang {
        Lang::Python
    }

    fn detect(
        &self,
        summary: &FuncSummary,
        _ast: tree_sitter::Node<'_>,
        file_bytes: &[u8],
    ) -> Option<FrameworkBinding> {
        let matches_source = source_imports_django_migration(file_bytes);
        if matches_source && name_is_django_migration_entry(&summary.name) {
            Some(FrameworkBinding {
                adapter: ADAPTER_NAME.to_owned(),
                kind: EntryKind::Migration {
                    version: extract_version(file_bytes),
                },
                route: None,
                request_params: Vec::new(),
                response_writer: None,
                middleware: Vec::new(),
            })
        } else {
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse_python(src: &[u8]) -> tree_sitter::Tree {
        let mut parser = tree_sitter::Parser::new();
        let lang = tree_sitter::Language::from(tree_sitter_python::LANGUAGE);
        parser.set_language(&lang).unwrap();
        parser.parse(src, None).unwrap()
    }

    #[test]
    fn fires_on_django_migration() {
        let src: &[u8] = b"from django.db import migrations\n\
            class Migration(migrations.Migration):\n    operations = [migrations.CreateModel(name='User', fields=[])]\n";
        let tree = parse_python(src);
        let summary = FuncSummary {
            name: "Migration".into(),
            ..Default::default()
        };
        let binding = MigrationDjangoAdapter
            .detect(&summary, tree.root_node(), src)
            .expect("django migration binds");
        assert_eq!(binding.adapter, "migration-django");
        assert!(matches!(binding.kind, EntryKind::Migration { .. }));
    }

    #[test]
    fn skips_unrelated_helper_in_django_migration_file() {
        let src: &[u8] = b"from django.db import migrations\n\
            class Migration(migrations.Migration):\n    operations = [migrations.CreateModel(name='User', fields=[])]\n\
            def normalize_name(name):\n    return str(name)\n";
        let tree = parse_python(src);
        let summary = FuncSummary {
            name: "normalize_name".into(),
            ..Default::default()
        };
        assert!(
            MigrationDjangoAdapter
                .detect(&summary, tree.root_node(), src)
                .is_none()
        );
    }
}
